import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import React, { useState ,useEffect} from 'react';
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home({ posts }) {
  const [query, setQuery] = useState("");
  const [check, setCheck] = useState("");
  const data = posts.data;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Your Profile!
        </h3>
          <div className={styles.grid}>
            <form>
              <input type="text" id="user" placeholder="Username"
                value={query} onChange={(event) => setQuery(event.target.value)}/>
              <input type="submit" value="Search" onClick={(event) => {
                event.preventDefault();
                setCheck(query)}}/>
            </form>
            {(posts.data.profile.username.includes(check)) ?
              <div href="https://nextjs.org/docs" className={styles.card} >
                <Image
                src={posts.data.profile.profile_picture_url}
                alt="Profile Picture"
                width={300}
                height={300}
              />
              <h4>{posts.data.profile.biography}</h4>
              <h4>Followers: </h4>
              <p>{posts.data.profile.followers_count}</p>
              <h4>Media-Count: </h4>
              <p>{posts.data.profile.media_count}</p>
              <h4>Username: </h4>
              <p>{posts.data.profile.username}</p>
              <p>
                <Link href="/posts/content">
                  <a>Go to the Content.</a>
                </Link>
              </p>
              </div>
              :  <div><p>Username not found!</p></div>
            }
          </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(){
  const data = {
    "platform":"Instagram",
    "username":"iamcloud.dev"
  };
  const headers = {
      "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTM2MjgzYzEzMWU5YTY0NzMzNmRmZmMiLCJ1aWQiOm51bGwsInVzZXJUeXBlIjoiQ29tcGFueSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNzIzMTM0Mn0.l9HHPRoREy_QNrjDg4oY91Y598yTSJS1kFCfGuWyQaw",
      "Content-Type": "application/json",
  };
  const posts = await axios.post("http://3.7.226.212/admin/discover/search-influencer", data, {headers});
  return {
    props: { posts: posts.data }
  }
}
